language: node_js
node_js:
  - '7'
install:
  - yarn install
script:
  - echo "no test"
before_deploy:
  - yarn build
deploy:
  skip_cleanup: true
  provider: surge
  project: ./build/
  domain: govfinder.surge.sh
  on:
    branch: master
